CREATE DATABASE ffw_task;
USE ffw_task;
CREATE TABLE IF NOT EXISTS users(
  id INT (11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE ,
  email VARCHAR(255) NOT NULL UNIQUE ,
  password VARCHAR (255)NOT NULL
);